source 'https://rubygems.org'

gem "jekyll", "~> 4.3.2" # installed by `gem jekyll`
gem "csv" # csv was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.4.0.
gem "base64" # base64 was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.4.0.
gem "bigdecimal" # bigdecimal was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.4.0.
# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2

gem "just-the-docs", "0.5.3" # pinned to the current release
# gem "just-the-docs"        # always download the latest release
